function OMEGA = computeOMEGA(PSI, OMEGA, U, V, dt, dx, dy, NY, NX, Visc)

OMEGA0 = OMEGA;
jj=2:NY-1;
ii=2:NX-1;
OMEGA(jj,ii) = OMEGA(jj,ii) + dt ...
                    * (-(U(jj,ii) .* ((OMEGA0(jj,ii+1) - OMEGA0(jj,ii-1)) / (2*dx))) ...
                        + ...
                       -(V(jj,ii) .* ((OMEGA0(jj+1,ii) - OMEGA0(jj-1,ii)) / (2*dy))) ...
                        + ...
                         Visc*(((OMEGA0(jj,ii-1) - 2*OMEGA0(jj,ii) + OMEGA0(jj,ii+1))/(dx^2)) ...
                                +...
                                ((OMEGA0(jj-1,ii) - 2*OMEGA0(jj,ii) + OMEGA0(jj+1,ii))/(dy^2))));