function OMEGA = computeOMEGA(PSI, OMEGA, U, V, dt, dx, dy, NY, NX, Visc)

jj=2:NY-1;
ii=2:NX-1;

OMEGA(jj,ii) = arrayfun(@omegaArrayFun, OMEGA(jj,ii), OMEGA(jj+1,ii), OMEGA(jj-1,ii), OMEGA(jj,ii+1), OMEGA(jj,ii-1), U(jj,ii), V(jj,ii), Visc, dx, dy, dt);
% OMEGA(jj,ii) = OMEGA(jj,ii) + dt ...
%                     * (-(U(jj,ii) .* ((OMEGA0(jj,ii+1) - OMEGA0(jj,ii-1)) / (2*dx))) ...
%                         + ...
%                        -(V(jj,ii) .* ((OMEGA0(jj+1,ii) - OMEGA0(jj-1,ii)) / (2*dy))) ...
%                         + ...
%                          Visc*(((OMEGA0(jj,ii-1) - 2*OMEGA0(jj,ii) + OMEGA0(jj,ii+1))/(dx^2)) ...
%                                 +...
%                                 ((OMEGA0(jj-1,ii) - 2*OMEGA0(jj,ii) + OMEGA0(jj+1,ii))/(dy^2))));


end

function OMEGAji = omegaArrayFun(OMEGAji,OMEGAjp1i,OMEGAjm1i,OMEGAjip1,OMEGAjim1,Uji,Vji,Visc,dx,dy,dt)
    OMEGAji = OMEGAji + dt ...
                * (-(Uji .* ((OMEGAjip1 - OMEGAjim1) / (2*dx))) ...
                    + ...
                   -(Vji .* ((OMEGAjp1i - OMEGAjm1i) / (2*dy))) ...
                    + ...
                     Visc*(((OMEGAjim1 - 2*OMEGAji + OMEGAjip1)/(dx^2)) ...
                            +...
                            ((OMEGAjm1i - 2*OMEGAji + OMEGAjp1i)/(dy^2))));
end