function OMEGA = computeOMEGA(PSI_jp1,PSI_jm1,PSI_ip1,PSI_im1, OMEGA_jp1, OMEGA_jm1, OMEGA_ip1, OMEGA_im1, OMEGA, dt, h, Visc)

OMEGA = OMEGA + dt * ...
           (-0.25*...
               (...
                   (PSI_ip1 - PSI_im1).*(OMEGA_jp1 - OMEGA_jm1)...
                        - ...
                   (PSI_jp1 - PSI_jm1).*(OMEGA_ip1 - OMEGA_im1)...
               )...
               /(h^2)...
               + ...
               Visc * ...
                    (OMEGA_jp1 + OMEGA_jm1 + OMEGA_ip1 + OMEGA_im1 - 4.0*OMEGA)...
               /(h^2)...
           ); % vorticity